name: GitHub Pages

on:
  push:
    branches:
      - main
      - add-github-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm run test:headless

      - name: Build
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: dist/angular-horizontal-scroll-example

      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/angular-horizontal-scroll-example
# name: GitHub Pages

# on:
#   push:
#     branches:
#       - main
#       - add-github-pages

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3

#       - name: Install dependencies
#         run: npm install

#       - name: Build project
#         run: npm run build

#       - name: Upload production-ready build files
#         uses: actions/upload-artifact@v3
#         with:
#           name: production-files
#           path: dist/angular-horizontal-scroll-example

#   deploy:
#     name: Deploy
#     needs: build
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'

#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v3
#         with:
#           name: production-files
#           path: ./dist/angular-horizontal-scroll-example

#       - name: Deploy to GitHub Pages
#         if: success()
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           folder: ./dist/angular-horizontal-scroll-example
